{
 "title": "Test-Cluster-TiDB-Resource-Control",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": "label_values(pd_cluster_status{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
   },
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": "label_values(pd_cluster_status, k8s_cluster)"
   },
   {
    "name": "tidb_instance",
    "label": "TiDB Instance",
    "query": "label_values(tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
   },
   {
    "name": "tikv_instance",
    "label": "TiKV Instance",
    "query": "label_values(tikv_engine_size_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
   },
   {
    "name": "resource_group",
    "label": "Resource Group",
    "query": "label_values(tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, resource_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Unit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RU Config",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "max by (resource_group, type) (resource_manager_server_group_config{type=\"priority\"})",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "max by (resource_group, type) (resource_manager_server_group_config{type=\"ru_capacity\"}) < bool 0",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "max by (resource_group, type) (resource_manager_server_group_config{type=\"ru_per_sec\"})",
       "legendFormat": "{{resource_group}}"
      }
     ]
    },
    {
     "title": "RU",
     "type": "graph",
     "description": "The metrics about request unit cost for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m])) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "RU Max (Max Cost During 20s Period)",
     "type": "graph",
     "description": "The max request unit cost for resource groups during in a period(20s).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(resource_manager_resource_unit_read_request_unit_max_per_sec{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}) by (resource_group)",
       "legendFormat": "{{resource_group}}-read"
      },
      {
       "expr": "sum(resource_manager_resource_unit_write_request_unit_max_per_sec{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}) by (resource_group)",
       "legendFormat": "{{resource_group}}-write"
      }
     ]
    },
    {
     "title": "RU Per Query",
     "type": "graph",
     "description": "The avg request unit cost for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (name) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "(sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m])) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m]))) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "RRU",
     "type": "graph",
     "description": "The read request unit cost for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "RRU Per Query",
     "type": "graph",
     "description": "The avg read request unit cost for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "WRU",
     "type": "graph",
     "description": "The write request unit cost for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "WRU Per Query",
     "type": "graph",
     "description": "The avg write request unit cost for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"|tp\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Count",
     "type": "graph",
     "description": "The metrics about kv request count for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group, type)",
       "legendFormat": "{{resource_group}}-{{type}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}-total"
      }
     ]
    },
    {
     "title": "KV Request Count Per Query",
     "type": "graph",
     "description": "The avg kv request count for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"read\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}-read"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"write\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}-write"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"read\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total-read"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total-write"
      }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "graph",
     "description": "The metrics about bytes read for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Read Per Query",
     "type": "graph",
     "description": "The avg bytes read for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "graph",
     "description": "The metrics about bytes written for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Written Per Query",
     "type": "graph",
     "description": "The avg bytes written for each query.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "KV CPU Time",
     "type": "graph",
     "description": "The metrics about kv cpu time for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_kv_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_kv_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "SQL CPU Time",
     "type": "graph",
     "description": "The metrics about sql cpu time for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_sql_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_sql_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Resource Groups",
     "type": "graph",
     "description": "The metrics about active resource groups.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resource_manager_client_resource_group_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}",
       "legendFormat": "{{instance}}-{{resource_group}}"
      }
     ]
    },
    {
     "title": "Total KV Request Count",
     "type": "graph",
     "description": "The metrics about total kv request count.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance) + sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name) + sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Failed KV Request Count",
     "type": "graph",
     "description": "The metrics about failed kv request count.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}[1m])) by (instance, resource_group, type)",
       "legendFormat": "{{resource_group}}-{{type}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Successful KV Request Wait Duration",
     "type": "graph",
     "description": "The metrics about successful kv request wait duration.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(resource_manager_client_request_success_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}[1m])) by (instance, resource_group, le))",
       "legendFormat": "{{instance}}-{{resource_group}}-99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(resource_manager_client_request_success_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}[1m])) by (instance, resource_group, le))",
       "legendFormat": "{{instance}}-{{resource_group}}-90"
      }
     ]
    },
    {
     "title": "Successful KV Request Count",
     "type": "graph",
     "description": "The metrics about successful kv request count.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}[1m])) by (instance, resource_group)",
       "legendFormat": "{{instance}}-{{resource_group}}"
      }
     ]
    },
    {
     "title": "Token Request Handle Duration",
     "type": "graph",
     "description": "The metrics about token request handle duration.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(resource_manager_client_token_request_duration_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(resource_manager_client_token_request_duration_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-999"
      }
     ]
    },
    {
     "title": "Token Request Count",
     "type": "graph",
     "description": "The metrics about token request count.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", type=\"success\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-successful"
      },
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", type=\"fail\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-failed"
      },
      {
       "expr": "sum(rate(resource_manager_client_token_request_resource_group{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", resource_group=~\"$resource_group\"}[1m])) by (instance, resource_group)",
       "legendFormat": "{{instance}}-{{resource_group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runaway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Max Duration",
     "type": "graph",
     "description": "TiDB max durations for different resource group",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", resource_group=~\"$resource_group\"}[1m])) by (le,resource_group))",
       "legendFormat": "{{resource_group}}"
      }
     ]
    },
    {
     "title": "Runaway Event",
     "type": "graph",
     "description": "Runaway manager events for different resource group",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_query_runaway_check{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"hit\", resource_group=~\"$resource_group\"}[5m])) by (resource_group)",
       "legendFormat": "{{resource_group}}-hit"
      },
      {
       "expr": "sum(rate(tidb_server_query_runaway_check{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type!=\"hit\", resource_group=~\"$resource_group\"}[5m])) by (resource_group, type, action)",
       "legendFormat": "{{resource_group}}-{{type}}-{{action}}"
      }
     ]
    },
    {
     "title": "Runaway Flusher Flush OPS",
     "type": "graph",
     "description": "The rate of runaway flusher flush operations per second, by flusher name and result.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_runaway_flusher_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, result)",
       "legendFormat": "{{name}}-{{result}}"
      }
     ]
    },
    {
     "title": "Runaway Flusher Add OPS",
     "type": "graph",
     "description": "The rate of records added to runaway flusher per second, by flusher name.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_runaway_flusher_add_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Runaway Flusher Batch Size",
     "type": "graph",
     "description": "The batch size distribution of runaway flusher flush operations.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_runaway_flusher_batch_size_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_runaway_flusher_batch_size_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P90"
      },
      {
       "expr": "sum(rate(tidb_server_runaway_flusher_batch_size_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name) / sum(rate(tidb_server_runaway_flusher_batch_size_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name)",
       "legendFormat": "{{name}}-avg"
      }
     ]
    },
    {
     "title": "Runaway Flusher Duration",
     "type": "graph",
     "description": "The duration of runaway flusher flush operations in seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_runaway_flusher_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_runaway_flusher_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P90"
      },
      {
       "expr": "sum(rate(tidb_server_runaway_flusher_duration_seconds_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name) / sum(rate(tidb_server_runaway_flusher_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name)",
       "legendFormat": "{{name}}-avg"
      }
     ]
    },
    {
     "title": "Runaway Flusher Interval",
     "type": "graph",
     "description": "The interval between consecutive runaway flusher flush operations in seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_runaway_flusher_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_runaway_flusher_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name, le))",
       "legendFormat": "{{name}}-P90"
      },
      {
       "expr": "sum(rate(tidb_server_runaway_flusher_interval_seconds_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name) / sum(rate(tidb_server_runaway_flusher_interval_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (name)",
       "legendFormat": "{{name}}-avg"
      }
     ]
    },
    {
     "title": "Runaway Syncer OPS",
     "type": "graph",
     "description": "The rate of runaway syncer operations per second, by instance and result.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_runaway_syncer_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, result)",
       "legendFormat": "{{instance}}-{{result}}"
      }
     ]
    },
    {
     "title": "Runaway Syncer Duration",
     "type": "graph",
     "description": "The duration of runaway syncer read operations in seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_runaway_syncer_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_runaway_syncer_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-P90"
      },
      {
       "expr": "sum(rate(tidb_server_runaway_syncer_duration_seconds_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance) / sum(rate(tidb_server_runaway_syncer_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-avg"
      }
     ]
    },
    {
     "title": "Runaway Syncer Interval",
     "type": "graph",
     "description": "The interval between consecutive runaway syncer operations in seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_runaway_syncer_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_runaway_syncer_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-P90"
      },
      {
       "expr": "sum(rate(tidb_server_runaway_syncer_interval_seconds_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance) / sum(rate(tidb_server_runaway_syncer_interval_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-avg"
      }
     ]
    },
    {
     "title": "Runaway Syncer Checkpoint",
     "type": "graph",
     "description": "The current checkpoint of runaway syncer, expressed as Unix milliseconds of the last synced start_time (watch) or done_time (watch_done). A value of 0 means no checkpoint has been established yet.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none", "label": "Unix ms" }
     ],
     "targets": [
      {
       "expr": "tidb_server_runaway_syncer_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Priority Task Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time by Priority",
     "type": "graph",
     "description": "The total CPU time cost by tasks of each priority.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_resource_control_priority_task_exec_duration{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, priority)",
       "legendFormat": "{{instance}}-{{priority}}"
      }
     ]
    },
    {
     "title": "CPU Quota Limit by Priority",
     "type": "graph",
     "description": "The CPU quota limiter applied to each priority.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_priority_quota_limit{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}",
       "legendFormat": "{{instance}}-{{priority}}"
      }
     ]
    },
    {
     "title": "Tasks Wait QPS by Priority",
     "type": "graph",
     "description": "Tasks number per second that triggers quota limiter wait",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_resource_control_priority_wait_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, priority)",
       "legendFormat": "{{instance}}-{{priority}}"
      }
     ]
    },
    {
     "title": "Priority Task Wait Duration",
     "type": "graph",
     "description": "The wait Duration of tasks that triggers quota limiter wait per priority",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_resource_control_priority_wait_duration_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance, priority, le))",
       "legendFormat": "{{instance}}-{{priority}}-P99"
      },
      {
       "expr": "sum(rate(tikv_resource_control_priority_wait_duration_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance, priority) / sum(rate(tikv_resource_control_priority_wait_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance, priority)",
       "legendFormat": "{{instance}}-{{priority}}-avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Task Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Background Task RU",
     "type": "graph",
     "description": "The total background task's request unit cost for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"background\", resource_group=~\"$resource_group\"}[1m])) by (resource_group) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"background\", resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"background\"}[1m])) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=~\"background\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Background Task Resource Utilization",
     "type": "graph",
     "description": "The resource(CPU, IO) utilization percentage and limit of background tasks.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_bg_resource_utilization{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Background Task IO Limit",
     "type": "graph",
     "description": "The total background task's io limit for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_background_quota_limiter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", resource_group=~\"$resource_group\", type=\"io\"}",
       "legendFormat": "{{resource_group}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task CPU Consumption",
     "type": "graph",
     "description": "The total background task's cpu consumption for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_resource_consumption{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", resource_group=~\"$resource_group\", type=\"cpu\"}[1m])",
       "legendFormat": "{{resource_group}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task CPU Limit",
     "type": "graph",
     "description": "The total background task's cpu limit for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_background_quota_limiter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", resource_group=~\"$resource_group\", type=\"cpu\"}",
       "legendFormat": "{{resource_group}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task IO Consumption",
     "type": "graph",
     "description": "The total background task's io consumption for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_resource_consumption{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", resource_group=~\"$resource_group\", type=\"io\"}[1m])",
       "legendFormat": "{{resource_group}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task Total Wait Duration",
     "type": "graph",
     "description": "The total background task's wait duration for all resource groups.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_task_wait_duration{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", resource_group=~\"$resource_group\"}[1m])",
       "legendFormat": "{{resource_group}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Duration",
     "type": "graph",
     "description": "The Duration of sql execute for different resource group",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (le,resource_group))",
       "legendFormat": "{{resource_group}}-P999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (le,resource_group))",
       "legendFormat": "{{resource_group}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (le,resource_group))",
       "legendFormat": "{{resource_group}}-P90"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (le,resource_group))",
       "legendFormat": "{{resource_group}}-P80"
      }
     ]
    },
    {
     "title": "Command Per Second",
     "type": "graph",
     "description": "MySQL commands processing numbers per second. See https://dev.mysql.com/doc/internals/en/text-protocol.html and https://dev.mysql.com/doc/internals/en/prepared-statements.html",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (result,resource_group)",
       "legendFormat": "{{resource_group}}-{{result}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "TiDB statement statistics",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_executor_statement_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (type,resource_group)",
       "legendFormat": "{{resource_group}}-{{type}}"
      },
      {
       "expr": "sum(rate(tidb_executor_statement_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}[1m])) by (resource_group)",
       "legendFormat": "{{resource_group}}-total"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "The number of connections to the TiDB server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}",
       "legendFormat": "{{instance}}--{{resource_group}}"
      },
      {
       "expr": "tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",instance=~\"$tidb_instance\",resource_group=~\"$resource_group\"}",
       "legendFormat": "{{resource_group}}--total"
      }
     ]
    },
    {
     "title": "Failed Query OPM",
     "type": "graph",
     "description": "The number of failed queries per minute",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_server_execute_error_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\",resource_group=~\"$resource_group\"}[1m])) by (type, instance,resource_group)",
       "legendFormat": "{{type}}-{{instance}}-{{resource_group}}"
      }
     ]
    }
   ]
  }
 ]
}